import { Order } from "./order-type";

export const MOCK_ORDERS: Order[] = [
  {
    id: "Z100001A01",
    clientName: "Client A",
    weightKg: 5,
    tariffPerKgUsd: 5.5,
    incomeUsd: 27.5,
    paidUsd: 0,
    remainingUsd: 27.5,
    status: "CREATED",
  },
  {
    id: "Z100002A02",
    clientName: "Client B",
    weightKg: 9,
    tariffPerKgUsd: 6.0,
    incomeUsd: 54,
    paidUsd: 20,
    remainingUsd: 34,
    status: "PICKED_UP",
  },
  {
    id: "Z100003A03",
    clientName: "Client C",
    weightKg: 14,
    tariffPerKgUsd: 6.5,
    incomeUsd: 91,
    paidUsd: 45,
    remainingUsd: 46,
    status: "IN_POST_WAREHOUSE",
  },
  {
    id: "Z100004A01",
    clientName: "Client D",
    weightKg: 7,
    tariffPerKgUsd: 7.0,
    incomeUsd: 49,
    paidUsd: 49,
    remainingUsd: 0,
    status: "IN_CUSTOMS",
  },
  {
    id: "Z100005A01",
    clientName: "Client E",
    weightKg: 11,
    tariffPerKgUsd: 6.2,
    incomeUsd: 68.2,
    paidUsd: 30,
    remainingUsd: 38.2,
    status: "IN_FLIGHT",
  },
  {
    id: "Z100006A01",
    clientName: "Client F",
    weightKg: 6,
    tariffPerKgUsd: 6.8,
    incomeUsd: 40.8,
    paidUsd: 40.8,
    remainingUsd: 0,
    status: "ARRIVED",
  },
  {
    id: "Z100007A01",
    clientName: "Client G",
    weightKg: 10,
    tariffPerKgUsd: 7.5,
    incomeUsd: 75,
    paidUsd: 50,
    remainingUsd: 25,
    status: "OUT_FOR_DELIVERY",
  },
  {
    id: "Z100008A01",
    clientName: "Client H",
    weightKg: 4,
    tariffPerKgUsd: 8.0,
    incomeUsd: 32,
    paidUsd: 32,
    remainingUsd: 0,
    status: "DELIVERED",
  },
  {
    id: "Z100009A01",
    clientName: "Client I",
    weightKg: 13,
    tariffPerKgUsd: 6.3,
    incomeUsd: 81.9,
    paidUsd: 81.9,
    remainingUsd: 0,
    status: "CLOSED",
  },
];
