import { Shipment } from "./shipment-types";

export const MOCK_SHIPMENTS: Shipment[] = [
  {
    id: "SH-001",
    postCompany: "Faravon",
    ordersCount: 18,
    totalWeightKg: 320,
    tariffPerKgUsd: 6.5,
    incomeUsd: 2080,
    expensesUsd: 1650,
    status: "IN_FLIGHT",
  },
  {
    id: "SH-002",
    postCompany: "Zamon",
    ordersCount: 12,
    totalWeightKg: 210,
    tariffPerKgUsd: 6.5,
    incomeUsd: 1365,
    expensesUsd: 1420,
    status: "IN_CUSTOMS_IN",
  },
  {
    id: "SH-003",
    postCompany: "Express Asia",
    ordersCount: 9,
    totalWeightKg: 155,
    tariffPerKgUsd: 7.2,
    incomeUsd: 1116,
    expensesUsd: 980,
    status: "READY",
  },
  {
    id: "SH-004",
    postCompany: "QuickPost",
    ordersCount: 22,
    totalWeightKg: 402,
    tariffPerKgUsd: 6.1,
    incomeUsd: 2452,
    expensesUsd: 2670,
    status: "IN_CUSTOMS_OUT",
  },
  {
    id: "SH-005",
    postCompany: "SilkWay Mail",
    ordersCount: 6,
    totalWeightKg: 98,
    tariffPerKgUsd: 8.0,
    incomeUsd: 784,
    expensesUsd: 620,
    status: "ARRIVED",
  },
  {
    id: "SH-006",
    postCompany: "Orient Express",
    ordersCount: 14,
    totalWeightKg: 260,
    tariffPerKgUsd: 6.8,
    incomeUsd: 1768,
    expensesUsd: 1500,
    status: "ON_WAREHOUSE",
  },
  {
    id: "SH-007",
    postCompany: "Nova Mail",
    ordersCount: 5,
    totalWeightKg: 74,
    tariffPerKgUsd: 9.0,
    incomeUsd: 666,
    expensesUsd: 590,
    status: "DELIVERING",
  },
  {
    id: "SH-008",
    postCompany: "Faravon",
    ordersCount: 11,
    totalWeightKg: 187,
    tariffPerKgUsd: 6.4,
    incomeUsd: 1197,
    expensesUsd: 1197,
    status: "CLOSED",
  },
  {
    id: "SH-009",
    postCompany: "Zamon",
    ordersCount: 7,
    totalWeightKg: 132,
    tariffPerKgUsd: 7.5,
    incomeUsd: 990,
    expensesUsd: 850,
    status: "DRAFT",
  },
];
