import { User, USER_ROLES } from "@/features/users/types/user.types";

export const mockUsers: User[] = [
  {
    id: 1,
    public_id: "A01",
    name: "pochta1",
    email: "pochta1@example.com",
    role: USER_ROLES.CARGO,
    status: "active",
    created_at: "2024-01-10",
  },
  {
    id: 2,
    public_id: "A02",
    name: "pochta2",
    email: "pochta2@example.com",
    role: USER_ROLES.CARGO,
    status: "active",
    created_at: "2024-02-05",
  },
  {
    id: 3,
    public_id: "B100",
    name: "prodavec1",
    email: "prodavec1@example.com",
    role: USER_ROLES.SELLER,
    status: "pending",
    created_at: "2024-02-20",
  },
  {
    id: 4,
    public_id: "B101",
    name: "prodavec2",
    email: "prodavec2@example.com",
    role: USER_ROLES.SELLER,
    status: "active",
    created_at: "2024-03-01",
  },
  {
    id: 5,
    public_id: "B103",
    name: "prodavec3",
    email: "prodavec3@example.com",
    role: USER_ROLES.SELLER,
    status: "blocked",
    created_at: "2024-03-10",
  },
  {
    id: 6,
    public_id: "C1001",
    name: "client1",
    email: "client1@example.com",
    role: USER_ROLES.CUSTOMER,
    status: "active",
    created_at: "2024-03-10",
  },
  {
    id: 7,
    public_id: "C1002",
    name: "prodavec3",
    email: "prodavec3@example.com",
    role: USER_ROLES.CUSTOMER,
    status: "blocked",
    created_at: "2024-03-10",
  },
  {
    id: 8,
    public_id: "C1003",
    name: "prodavec3",
    email: "prodavec3@example.com",
    role: USER_ROLES.CUSTOMER,
    status: "blocked",
    created_at: "2024-03-10",
  },
  {
    id: 9,
    public_id: "C1004",
    name: "prodavec3",
    email: "prodavec3@example.com",
    role: USER_ROLES.CUSTOMER,
    status: "blocked",
    created_at: "2024-03-10",
  },
  {
    id: 10,
    public_id: "C1005",
    name: "prodavec3",
    email: "prodavec3@example.com",
    role: USER_ROLES.CUSTOMER,
    status: "blocked",
    created_at: "2024-03-10",
  },
];
