import { Product } from "./types/product.types";

export type ProductRow = {
  id: string;
  sub_category: string;
  series: number;
  count_of_series: number;
  price: number;
  sizes: { size: string; quantity: number }[];
  quantity: number;
  photo_url: string;
  sold_series: number;
  sold_units: number;
  sold_amount: number;
};

export const productTableMock: ProductRow[] = [
  {
    id: "P10001A001",
    sub_category: "Футболки",
    series: 1,
    count_of_series: 10,
    sold_series: 5,
    sold_units: 50,
    price: 15,
    sizes: [
      { size: "S", quantity: 2 },
      { size: "M", quantity: 3 },
      { size: "L", quantity: 5 },
    ],
    quantity: 0,
    sold_amount: 750,
    photo_url: "/products-photo/bag.jpg",
  },
  {
    id: "P10002A001",
    sub_category: "Одежда",
    series: 1,
    count_of_series: 5,
    sold_series: 3,
    sold_units: 12,
    price: 25,
    sizes: [
      { size: "M", quantity: 2 },
      { size: "L", quantity: 2 },
    ],
    quantity: 0,
    sold_amount: 300,
    photo_url: "/products-photo/clothes.jpg",
  },
  {
    id: "P10001A002",
    sub_category: "Верхняя одежда",
    series: 2,
    count_of_series: 2,
    sold_series: 1,
    sold_units: 4,
    price: 60,
    sizes: [
      { size: "M", quantity: 1 },
      { size: "L", quantity: 2 },
      { size: "XL", quantity: 1 },
    ],
    quantity: 0,
    sold_amount: 240,
    photo_url: "/products-photo/coat.jpg",
  },
  {
    id: "P10002A002",
    sub_category: "Костюмы",
    series: 1,
    count_of_series: 2,
    sold_series: 0,
    sold_units: 0,
    price: 80,
    sizes: [
      { size: "S", quantity: 1 },
      { size: "M", quantity: 1 },
    ],
    quantity: 0,
    sold_amount: 0,
    photo_url: "/products-photo/dvoyka.jpg",
  },
  {
    id: "P10003A002",
    sub_category: "Платья",
    series: 1,
    count_of_series: 6,
    sold_series: 5,
    sold_units: 30,
    price: 70,
    sizes: [
      { size: "S", quantity: 2 },
      { size: "M", quantity: 2 },
      { size: "L", quantity: 2 },
    ],
    quantity: 0,
    sold_amount: 2100,
    photo_url: "/products-photo/platye.jpg",
  },
];

export const fakeProducts: Product[] = [
  {
    id: "P10001A001",
    name: "Сумка",
    category: "Одежда",
    unit: "Серия",
    quantity: 7,
    price: 8,
    photo_url: "/products-photo/bag.jpg",
    comment: "Сумка белый, черный, коричневый только в розницу",
    is_public: false,
  },
  {
    id: "P10002A001",
    name: "Рубашка",
    category: "Одежда",
    unit: "Серия",
    quantity: 2,
    price: 12,
    photo_url: "/products-photo/clothes.jpg",
    comment: "Рубашка 3 цветов, не штучно!!!",
    is_public: false,
  },
  {
    id: "P10001A002",
    name: "Пальто",
    category: "Одежда",
    unit: "Серия",
    quantity: 4,
    price: 3,
    photo_url: "/products-photo/coat.jpg",
    comment: "Пальто разных цветов",
    is_public: false,
  },
  {
    id: "P10002A002",
    name: "Двойка",
    category: "Одежда",
    unit: "Серия",
    quantity: 6,
    price: 3,
    photo_url: "/products-photo/dvoyka.jpg",
    comment: "Двойка только в розницу",
    is_public: false,
  },
  {
    id: "P10003A002",
    name: "Платье",
    category: "Одежда",
    unit: "Серия",
    quantity: 3,
    price: 3,
    photo_url: "/products-photo/platye.jpg",
    is_public: false,
  },

  // --- новые товары ---
  {
    id: "P10004A001",
    name: "Брюки",
    category: "Одежда",
    unit: "Серия",
    quantity: 5,
    price: 4,
    photo_url: "/products-photo/bryuki-1.jpg",
    comment: "Брюки классические",
    is_public: false,
  },
  {
    id: "P10004A002",
    name: "Брюки",
    category: "Одежда",
    unit: "Серия",
    quantity: 5,
    price: 4,
    photo_url: "/products-photo/bryuki-2.jpg",
    comment: "Брюки повседневные",
    is_public: false,
  },
  {
    id: "P10005A001",
    name: "Двойка",
    category: "Одежда",
    unit: "Серия",
    quantity: 4,
    price: 5,
    photo_url: "/products-photo/dvoyka-2.jpg",
    comment: "Двойка обновленная модель",
    is_public: false,
  },
  {
    id: "P10006A001",
    name: "Футболка",
    category: "Одежда",
    unit: "Серия",
    quantity: 10,
    price: 2,
    photo_url: "/products-photo/futbolka-1.jpg",
    comment: "Футболка базовая",
    is_public: false,
  },
  {
    id: "P10007A001",
    name: "Пальто",
    category: "Одежда",
    unit: "Серия",
    quantity: 3,
    price: 6,
    photo_url: "/products-photo/palto-2.jpg",
    comment: "Пальто модель 2",
    is_public: false,
  },
  {
    id: "P10007A002",
    name: "Пальто",
    category: "Одежда",
    unit: "Серия",
    quantity: 3,
    price: 6,
    photo_url: "/products-photo/palto-3.jpg",
    comment: "Пальто модель 3",
    is_public: false,
  },
  {
    id: "P10007A003",
    name: "Пальто",
    category: "Одежда",
    unit: "Серия",
    quantity: 3,
    price: 6,
    photo_url: "/products-photo/palto-4.jpg",
    comment: "Пальто модель 4",
    is_public: false,
  },
];

export const ALL_SIZES = [
  "Станд.",
  "3XS",
  "2XS",
  "XS",
  "S",
  "M",
  "L",
  "XL",
  "2XL",
  "3XL",
  "4XL",
  "5XL",
  "6XL",
  "0-3мс.",
  "3-6мс.",
  "6-9мс.",
  "9-12мс.",
  "12-18мс.",
  "18-24мс.",
  "2-3гд.",
  "3-4гд.",
  "4-5гд.",
  "5-6гд.",
  ...Array.from({ length: 61 }, (_, i) => String(i)),
];

export const CATEGORY_LIST = ["Мужской", "Женский", "Детский", "Дом"];
export const SUB_CATEGORY_LIST = [
  "Футболки",
  "Рубашки",
  "Свитшоты",
  "Куртки",
  "Пальто",
  "Джинсы",
  "Брюки",
  "Шорты",
  "Юбки",
];
