import { Product } from "./types/product.types";

export const fakeProducts: Product[] = [
  {
    id: 1,
    name: "Сумка",
    category: "Одежда",
    unit: "Серия",
    quantity: 7,
    price: 8,
    photo_url: "/products-photo/bag.jpg",
    comment: "Сумка белый, черный, коричневый только в розницу",
    is_public: false,
  },
  {
    id: 2,
    name: "Рубашка",
    category: "Одежда",
    unit: "Серия",
    quantity: 300,
    price: 12,
    photo_url: "/products-photo/clothes.jpg",
    comment: "Рубашка 3 цветов, не штучно!!!",
    is_public: false,
  },
  {
    id: 3,
    name: "Пальто",
    category: "Одежда",
    unit: "Серия",
    quantity: 240,
    price: 3,
    photo_url: "/products-photo/coat.jpg",
    is_public: false,
  },
  {
    id: 4,
    name: "Двойка",
    category: "Одежда",
    unit: "Серия",
    quantity: 240,
    price: 3,
    photo_url: "/products-photo/dvoyka.jpg",
    is_public: false,
  },
  {
    id: 5,
    name: "Платье",
    category: "Одежда",
    unit: "Серия",
    quantity: 240,
    price: 3,
    photo_url: "/products-photo/platye.jpg",
    is_public: false,
  },
];
